# 服务器相关配置
server:
  port: 8989
  servlet:
    context-path: /ems191206
    jsp:
      init-parameters:
        development: true
# spring相关配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems191206?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    host: 39.107.12.254
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
  mvc:
    view:
      suffix: .jsp
      prefix: /
# mybatis相关配置
mybatis:
  type-aliases-package: com.ix.entity
  mapper-locations: classpath:com/ix/mapper/*Mapper.xml
